apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-website
  namespace: networking-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: company-website
  template:
    metadata:
      labels:
        app: company-website
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
